int32 Free = 0
int32 Unknown = 1
int32 Obstacle = 2
int32 Object = 3

int32 BLUE = 255
int32 GREEN = 65280
int32 CYAN = 65535
int32 RED = 16711680
int32 MAGENTA = 16711935
int32 YELLOW = 16776960
int32 UNDEF = -1

int32 BLUE_ID = 0
int32 GREEN_ID = 1
int32 CYAN_ID = 2
int32 RED_ID = 3
int32 MAGENTA_ID = 4
int32 YELLOW_ID = 5
int32 UNDEF_ID = 6

string BLUE_HEX = "0000ff"
string GREEN_HEX = "00ff00"
string CYAN_HEX = "00ffff"
string RED_HEX = "ff0000"
string MAGENTA_HEX = "ff00ff"
string YELLOW_HEX = "ffff00"

float32 average_z
float32 highest_z
int32 treshold_min_point
bool marked 
int32 state
int32[] points
